# Site settings.
title: John's Homepage
author: John Hook
email: john2hook@gmail.com
description: This is my homepage. My homepage is amazing.

github_username: jhook1

# Build settings
theme: minima
plugins:
#  - jekyll-feed
